### ISSUE TITLE
Default download is not working 

### ISSUE THREAD

**Issue by yurii-luchkiv** [cristijora/vue-paper-dashboard#25]
`npm install`
`npm run dev` 

Output: 

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/yuriiluchkiv/Development/workspace-globalfreight/globalfreight-creative-tim-vue-paper-dashboard/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/yuriiluchkiv/Development/workspace-globalfreight/globalfreight-creative-tim-vue-paper-dashboard/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/yuriiluchkiv/Development/workspace-globalfreight/globalfreight-creative-tim-vue-paper-dashboard/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/yuriiluchkiv/Development/workspace-globalfreight/globalfreight-creative-tim-vue-paper-dashboard/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/Users/yuriiluchkiv/Development/workspace-globalfreight/globalfreight-creative-tim-vue-paper-dashboard/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/yuriiluchkiv/Development/workspace-globalfreight/globalfreight-creative-tim-vue-paper-dashboard/node_modules/eslint-loader/index.js:213:21)

Added: 
.eslintrc.js

// http://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true,
  },
  // https://github.com/standard/standard/blob/master/docs/RULES-en.md
  extends: 'standard',
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

AND

"babel-eslint": "^7.1.1" in package.json in "devDependencies" section. 

Can you verify? Thanks

**Comment by cristijora** [comment]
Hi @yurii-luchkiv 
The default download downloads the current repo which already has an eslint config specified in a json
https://github.com/cristijora/vue-paper-dashboard/blob/master/.eslintrc.json

Did it work with the default `.json` file ? You can also write in russian if that is easier. I understand russian.
Some info about node version and OS would also help

**Comment by yurii-luchkiv** [comment]
OS: 10.13.1
Node: v7.10.0
npm: 5.3.0

I downloaded probaby 5-10 days ago, only today unpacked and start working. Maybe I made mistake, cause now I download and everything is in place 👍
